// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloudNimble.BindingRedirectDoctor
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFixRedirectsCommandPackageString = "402b69c6-e132-417a-a347-22bea9368042";
        public static Guid guidFixRedirectsCommandPackage = new Guid(guidFixRedirectsCommandPackageString);

        public const string guidUIContextString = "f3cd4159-cc79-445b-bd4c-8bf9e0c589bb";
        public static Guid guidUIContext = new Guid(guidUIContextString);

        public const string guidFixRedirectsCommandPackageCmdSetString = "32d54385-5980-4bbb-8399-102a06ddb174";
        public static Guid guidFixRedirectsCommandPackageCmdSet = new Guid(guidFixRedirectsCommandPackageCmdSetString);

        public const string guidImagesString = "4a9e2acb-8bf3-497c-b0d8-834ebee79547";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int FixRedirectsCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}