// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloudNimble.BindingRedirectDoctor
{
    internal sealed partial class Vsix
    {
        public const string Id = "3d111d8d-7d15-4c6e-8ca3-494426e539ff";
        public const string Name = "BindingRedirects Doctor";
        public const string Description = @"Cleans and sorts the Assembly Binding Redirects in your projects to make them more manageable.";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "Robert McLaws";
        public const string Tags = "web.config, assembly binding redirects, binding redirects, assembly binding";
    }
}
